version: "3.9"  
services:
  web:
    image: cientopolis/scolr:latest
    read_only: true
    restart: unless-stopped
    ports:
        - "8080:8080"
    environment: 
      SMTP_SERVER: your-smtp-server-ip
      ADMIN_EMAIL: admin@mail.com
    volumes:
        - type: bind
          source: ./data
          target: /opt/pharo/data
