redering
renderBackgroundOn: stream
	stream
		nextPutAll:
			'\section{Background}

In this section you provide more background about your research domain. If the reader needs to know something in order to understand your review, this is the moment.

This is also the place where you introduce the various dimensions you will later use to analyze the articles. These can be the questions you what to answer or any other crosscutting aspect you plan to observe in articles trying to identify patterns. 

'