styles
style 
	^ 'body {
  font-family: Sans-Serif;
}

table {
border-width: 1px;
border-style: solid;
}

td {
border-width: 1px;
border-style: solid;
}

tr.in {
background-color: rgba(0, 128, 0, 0.37);
}

tr.out {
background-color: rgba(255, 0, 0, 0.59);
}

tr.disagree {
background-color: rgba(231, 209, 56, 0.5);
}

div.login {
    width: 150px;
    padding: 25px;
    border: 2px solid navy;
    margin: auto;
}

', self styleForLoginScreen. 
