styles
styleForLoginScreen

^'div.loginbox {
background-color: #F7F7F7;
padding: 20px 25px 30px;
margin: 0px auto 25px;
width: 304px;
border-radius: 2px;
box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.3);
}

.loginlabel { 
font-size: 16px;
font-weight: bold;
text-align: center;
margin: 10px 0px 0px;
min-height: 1em;
font-family: Arial,sans-serif;
color: #404040;
direction: ltr;
 }

.loginfield {  
   margin-top: -1px;
direction: ltr;
height: 44px;
font-size: 16px;
width: 100%;
display: block;
margin-bottom: 10px;
z-index: 1;
position: relative;
box-sizing: border-box;
width: 100%;
display: block;
margin-bottom: 10px;
z-index: 1;
position: relative;
box-sizing: border-box;
}

.loginsubmitbuton{
	width: 100%;
display: block;
margin-bottom: 10px;
z-index: 1;
position: relative;
box-sizing: border-box;
padding: 0px;
font-family: Arial,sans-serif;
font-size: 13px;
border: 1px solid #3079ED;
color: #FFF;
text-shadow: 0px 1px rgba(0, 0, 0, 0.1);
background-color: #4D90FE;
background-image: -moz-linear-gradient(center top , #4D90FE, #4787ED);
min-width: 46px;
text-align: center;
font-weight: 700;
line-height: 36px;
border-radius: 3px;
transition: all 0.218s ease 0s;
-moz-user-select: none;
cursor: default;
direction: ltr;
}'
