SystemOrganization addCategory: #'Scolr-seaside'!
SystemOrganization addCategory: #'Scolr-seaside-Manifest'!
SystemOrganization addCategory: #'Scolr-seaside-components'!
SystemOrganization addCategory: #'Scolr-seaside-configuration'!
SystemOrganization addCategory: #'Scolr-seaside-errors'!
SystemOrganization addCategory: #'Scolr-seaside-subcomponents'!
SystemOrganization addCategory: #'Scolr-seaside-tests'!
SystemOrganization addCategory: #'Scolr-seaside-utilities'!
