rendering
renderSynthesisAndAnalysisOn: html
	html heading
		level: 2;
		with: 'Synthesis and analysis'.
	html paragraph: [ html emphasis: 'Export this report and use any word processor you like to review your notes, and report your key findings.' ].
	html paragraph: [ html emphasis: 'Remember to target the research questions you used to focus this review.' ].
	html
		paragraph: [ html emphasis: 'You can organize this section following the same dimensions you used in the reviews.' ].
	html
		paragraph: [ html
				emphasis:
					'You can use the tags attached to articles during the review phase. If several articles shared a tag, it means there is a pattern to discuss. Just for inspiration, these are the most frequently used tags (3+ articles) and the articles that had them.' ]