callbacks
edit

	title := self coReview title.
	objective := self coReview objective.
	researchQuestions := self coReview researchQuestions.
	terms := self coReview terms.
	basicSearchQuery := self coReview basicSearchQuery.
	databases := self coReview databases.
	inclusionCriteria := self coReview inclusionCriteria.
	exclusionCriteria := self coReview exclusionCriteria.
	notes := self coReview notes.
	isEditing := true